// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp916CYDQ2PSS1j-e3k2bWKPwO1t6p8GI',
    appId: '1:246865564916:android:55ce41b557d3a2a5853aa1',
    messagingSenderId: '246865564916',
    projectId: 'learnify-6571a',
    storageBucket: 'learnify-6571a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5sVg2K_1uaVOJh6d4VJUy8VvYS6BMfOM',
    appId: '1:246865564916:ios:f70eff171f96ab1c853aa1',
    messagingSenderId: '246865564916',
    projectId: 'learnify-6571a',
    storageBucket: 'learnify-6571a.firebasestorage.app',
    iosBundleId: 'com.example.learnify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlSzGSMAjfiPeCu1cIjG4Zxb9atr0jpI',
    appId: '1:246865564916:web:d9a7117954c5df40853aa1',
    messagingSenderId: '246865564916',
    projectId: 'learnify-6571a',
    authDomain: 'learnify-6571a.firebaseapp.com',
    storageBucket: 'learnify-6571a.firebasestorage.app',
    measurementId: 'G-V0MV4GFZXM',
  );

}